CREATE TABLE tb_doctor (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    crm VARCHAR(20) UNIQUE NOT NULL,
    specialty VARCHAR(100) NOT NULL,
    role VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    birthday DATE,
    password VARCHAR(255) NOT NULL
);
